//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comman_fruit_veg
    {
        public int fv { get; set; }
        public Nullable<int> Fruit_id { get; set; }
        public Nullable<int> veg_Id { get; set; }
    
        public virtual fruits_tbl fruits_tbl { get; set; }
        public virtual vegerables_tbl vegerables_tbl { get; set; }
    }
}
