//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_company.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ankit_TaskEntities : DbContext
    {
        public Ankit_TaskEntities()
            : base("name=Ankit_TaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fruits_tbl> fruits_tbl { get; set; }
        public virtual DbSet<vegerables_tbl> vegerables_tbl { get; set; }
        public virtual DbSet<comman_fruit_veg> comman_fruit_veg { get; set; }
    }
}
