//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_company.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vegerables_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vegerables_tbl()
        {
            this.fruits_tbl = new HashSet<fruits_tbl>();
            this.comman_fruit_veg = new HashSet<comman_fruit_veg>();
        }
    
        public int veg_Id { get; set; }

        [Required(ErrorMessage = "Please enter Vegitable name")]

        public string veg_Name { get; set; }
        [Required(ErrorMessage = "Please select fruit name")]

        public Nullable<int> Fruit_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fruits_tbl> fruits_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comman_fruit_veg> comman_fruit_veg { get; set; }
        public virtual fruits_tbl fruits_tbl1 { get; set; }
    }
}
